### ISSUE TITLE
blogs

### ISSUE THREAD

**Issue by TerryLines** [Indicative-Data-Science/Website#1]
2 blogs for you. The images need resizing, but I left to you as they need previewing in the website plus not sure what methodology you might prefer.

[gnssmapper.md](https://github.com/Indicative-Data-Science/Website/files/6376507/gnssmapper.md)
[osblog.md](https://github.com/Indicative-Data-Science/Website/files/6376508/osblog.md)

![3d](https://user-images.githubusercontent.com/43879942/116072219-bbb59480-a686-11eb-9d66-828b84286365.png)
![fit](https://user-images.githubusercontent.com/43879942/116072223-bc4e2b00-a686-11eb-849a-d8c80ff6bea6.png)

images from web:

![women_using_smartphone_to_find_city_sites_01-04-2018_lbs_01](https://user-images.githubusercontent.com/25252172/116252249-4cfc3800-a767-11eb-9abe-de3b28821323.jpg)

![gsa_mapping_77](https://user-images.githubusercontent.com/25252172/116252759-c5fb8f80-a767-11eb-8054-cab848115bc3.jpg)

**Comment by dataandcrowd** [comment]
Thank you terry. You can check the contents on our website within 30mins. https://ggds.netlify.app/
